// concept/components/OracleChat.tsx
import React, { useState, useEffect, useRef } from 'react';
import { Send, Terminal, Sparkles, AlertTriangle } from 'lucide-react';
import { streamOracleResponse } from '../services/geminiService';
import { ChatMessage } from '../types';

export const OracleChat: React.FC = () => {
  const [input, setInput] = useState('');
  const [messages, setMessages] = useState<ChatMessage[]>([
    {
      id: 'init',
      role: 'model',
      text: 'Greetings, Digital Argonaut. I am the Guardian of the Cipher. Query me regarding the Quest, the Lore, or the challenges that await.',
    },
  ]);
  const [isLoading, setIsLoading] = useState(false);
  const scrollRef = useRef<HTMLDivElement>(null);

  // Locked Maritime Theme
  const theme = {
    border: 'border-cyan-500',
    text: 'text-cyan-400',
    bg: 'bg-cyan-950/20',
    button: 'bg-cyan-600 hover:bg-cyan-500',
    userBubble: 'bg-cyan-900/40',
    modelBubble: 'bg-slate-900/90',
  };

  useEffect(() => {
    if (scrollRef.current) {
      scrollRef.current.scrollTop = scrollRef.current.scrollHeight;
    }
  }, [messages]);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!input.trim() || isLoading) return;

    const userMsg: ChatMessage = {
      id: Date.now().toString(),
      role: 'user',
      text: input,
    };

    setMessages((prev) => [...prev, userMsg]);
    setInput('');
    setIsLoading(true);

    const modelMsgId = (Date.now() + 1).toString();
    setMessages((prev) => [
      ...prev,
      { id: modelMsgId, role: 'model', text: '', isStreaming: true },
    ]);

    let fullText = '';
    
    const history = messages.map(m => ({ role: m.role, text: m.text }));
    history.push({ role: userMsg.role, text: userMsg.text });

    await streamOracleResponse(history, (chunk) => {
      fullText += chunk;
      setMessages((prev) =>
        prev.map((m) =>
          m.id === modelMsgId ? { ...m, text: fullText } : m
        )
      );
    });

    setMessages((prev) =>
      prev.map((m) => (m.id === modelMsgId ? { ...m, isStreaming: false } : m))
    );
    setIsLoading(false);
  };

  return (
    <div className={`w-full max-w-4xl mx-auto border ${theme.border} rounded-sm overflow-hidden backdrop-blur-md relative font-mono shadow-[0_0_30px_rgba(6,182,212,0.1)]`}>
        {/* Header */}
        <div className={`p-4 ${theme.bg} border-b ${theme.border} flex items-center justify-between`}>
            <div className="flex items-center gap-2">
                <Terminal className={`w-5 h-5 ${theme.text}`} />
                <h3 className={`text-lg font-bold ${theme.text} uppercase tracking-widest`}>
                    Oracle Uplink
                </h3>
            </div>
            <div className="flex items-center gap-2 text-xs opacity-70 font-mono">
                <span className="animate-pulse w-2 h-2 rounded-full bg-cyan-400 shadow-[0_0_10px_rgba(34,211,238,0.8)]"></span>
                SYSTEM ONLINE
            </div>
        </div>

        {/* Chat Area */}
        <div 
            ref={scrollRef}
            className="h-[400px] overflow-y-auto p-6 space-y-6 bg-black/80 scrollbar-hide"
        >
            {messages.map((msg) => (
                <div
                    key={msg.id}
                    className={`flex ${msg.role === 'user' ? 'justify-end' : 'justify-start'}`}
                >
                    <div
                        className={`max-w-[85%] p-4 border border-white/10 ${
                            msg.role === 'user' 
                                ? `${theme.userBubble} border-cyan-500/30 rounded-tl-lg rounded-tr-lg rounded-bl-lg` 
                                : `${theme.modelBubble} border-white/5 rounded-tr-lg rounded-br-lg rounded-bl-lg`
                        }`}
                    >
                        {msg.role === 'model' && (
                            <div className={`text-[10px] ${theme.text} mb-2 flex items-center gap-2 tracking-widest uppercase opacity-80`}>
                                <Sparkles className="w-3 h-3" /> Guardian Node
                            </div>
                        )}
                        <p className="whitespace-pre-wrap leading-relaxed text-sm md:text-base text-gray-200">{msg.text}</p>
                        {msg.isStreaming && (
                            <span className={`inline-block w-2 h-4 ml-1 ${theme.button} animate-pulse`}></span>
                        )}
                    </div>
                </div>
            ))}
        </div>

        {/* Input Area */}
        <form onSubmit={handleSubmit} className={`p-4 bg-black border-t ${theme.border}`}>
            <div className="flex gap-4">
                <div className="flex-1 relative">
                    <input
                        type="text"
                        value={input}
                        onChange={(e) => setInput(e.target.value)}
                        placeholder="Establish connection..."
                        className="w-full bg-slate-900/50 border border-white/20 p-4 font-mono text-sm focus:outline-none focus:border-cyan-500 text-cyan-100 placeholder-cyan-900/50 transition-colors"
                    />
                    <div className="absolute right-0 top-0 bottom-0 w-2 bg-white/5"></div>
                </div>
                <button
                    type="submit"
                    disabled={isLoading}
                    className={`px-6 py-2 text-white font-bold uppercase tracking-wider transition-all disabled:opacity-50 hover:shadow-[0_0_20px_rgba(8,145,178,0.4)] ${theme.button}`}
                >
                    <Send className="w-5 h-5" />
                </button>
            </div>
            <div className="mt-2 text-[10px] text-gray-600 flex items-center gap-1 font-mono uppercase">
                 <AlertTriangle className="w-3 h-3" /> Secure Channel // Response Variance Expected
            </div>
        </form>
    </div>
  );
};

// src/lib/components/OracleChat.svelte
<script lang="ts">
  import type { ColorMode, ChatMessage } from "$lib/types";
  import { Send, Terminal, Sparkles } from "lucide-svelte";

  let { colorMode }: { colorMode: ColorMode } = $props();

  let input = $state("");
  let messages = $state<ChatMessage[]>([
    {
      id: "init",
      role: "model",
      text: "Greetings, Digital Argonaut. I am the Guardian of the Cipher. Query me regarding the Quest, the Lore, or the challenges that await.",
    },
  ]);
  let isLoading = $state(false);
  let scrollContainer: HTMLDivElement | null = $state(null);

  const themeColors = {
    blue: {
      border: "border-cyan-500",
      text: "text-cyan-400",
      bg: "bg-cyan-950/30",
      button: "bg-cyan-600 hover:bg-cyan-500",
      userBubble: "bg-cyan-900/50",
      modelBubble: "bg-slate-900/80",
    },
    gold: {
      border: "border-amber-500",
      text: "text-amber-400",
      bg: "bg-amber-950/30",
      button: "bg-amber-600 hover:bg-amber-500",
      userBubble: "bg-amber-900/50",
      modelBubble: "bg-stone-900/80",
    },
  };

  let currentTheme = $derived(themeColors[colorMode]);

  $effect(() => {
    messages;
    if (scrollContainer) {
      scrollContainer.scrollTop = scrollContainer.scrollHeight;
    }
  });

  const handleSubmit = async (e: Event) => {
    e.preventDefault();
    if (!input.trim() || isLoading) return;

    const userText = input; // capture value
    const userMsg: ChatMessage = {
      id: Date.now().toString(),
      role: "user",
      text: userText,
    };

    const botMsgId = (Date.now() + 1).toString();
    const botMsg: ChatMessage = {
      id: botMsgId,
      role: "model",
      text: "",
      isStreaming: true,
    };

    messages = [...messages, userMsg, botMsg];
    input = "";
    isLoading = true;

    try {
      const historyForApi = messages.filter((m) => m.id !== botMsgId);

      const response = await fetch("/api/oracle", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ history: historyForApi }),
      });

      if (!response.body) throw new Error("No response body");
      const reader = response.body.getReader();
      const decoder = new TextDecoder();

      while (true) {
        const { done, value } = await reader.read();
        if (done) break;
        const chunk = decoder.decode(value, { stream: true });
        messages = messages.map((m) =>
          m.id === botMsgId ? { ...m, text: m.text + chunk } : m,
        );
      }
    } catch (e) {
      console.error(e);
      messages = messages.map((m) =>
        m.id === botMsgId
          ? { ...m, text: "\n[CONNECTION INTERRUPTED] The Cipher is unstable." }
          : m,
      );
    }

    messages = messages.map((m) =>
      m.id === botMsgId ? { ...m, isStreaming: false } : m,
    );
    isLoading = false;
  };
</script>

<div
  class={`w-full max-w-2xl mx-auto border backdrop-blur-md rounded-lg overflow-hidden flex flex-col h-[600px] shadow-2xl ${currentTheme.border} ${currentTheme.bg}`}
>
  <!-- Header -->
  <div
    class={`p-4 border-b border-white/10 flex items-center gap-3 ${currentTheme.bg}`}
  >
    <div class={`p-2 rounded-full bg-black/40 border border-white/10`}>
      <Sparkles class={`w-5 h-5 ${currentTheme.text}`} />
    </div>
    <div>
      <h3 class={`font-mono font-bold text-lg text-white`}>Oracle Link</h3>
      <div class="flex items-center gap-2">
        <span class="relative flex h-2 w-2">
          <span
            class={`animate-ping absolute inline-flex h-full w-full rounded-full opacity-75 ${colorMode === "blue" ? "bg-cyan-400" : "bg-amber-400"}`}
          ></span>
          <span
            class={`relative inline-flex rounded-full h-2 w-2 ${colorMode === "blue" ? "bg-cyan-500" : "bg-amber-500"}`}
          ></span>
        </span>
        <span
          class={`text-[10px] uppercase tracking-widest ${currentTheme.text}`}
          >Online</span
        >
      </div>
    </div>
  </div>

  <!-- Messages -->
  <div
    bind:this={scrollContainer}
    class="flex-1 overflow-y-auto p-4 space-y-4 font-mono text-sm scrollbar-hide"
  >
    {#each messages as msg (msg.id)}
      <div
        class={`flex ${msg.role === "user" ? "justify-end" : "justify-start"}`}
      >
        <div
          class={`max-w-[85%] p-4 rounded-lg border border-white/5 ${msg.role === "user" ? currentTheme.userBubble + " rounded-tr-none" : currentTheme.modelBubble + " rounded-tl-none"}`}
        >
          {#if msg.role === "model"}
            <div
              class="flex items-center gap-2 mb-1 opacity-50 text-xs uppercase tracking-widest"
            >
              <Terminal class="w-3 h-3" /> Guardian
            </div>
          {/if}
          <p class="whitespace-pre-wrap leading-relaxed">{msg.text}</p>
          {#if msg.isStreaming}
            <span class="animate-pulse">_</span>
          {/if}
        </div>
      </div>
    {/each}
    {#if isLoading && !messages.some((m) => m.isStreaming && m.role === "model")}
      <!-- Loading state that doesn't track streaming yet? -->
    {/if}
  </div>

  <!-- Input -->
  <form
    onsubmit={handleSubmit}
    class="p-4 border-t border-white/10 bg-black/60"
  >
    <div class="relative flex gap-2">
      <div
        class="absolute inset-y-0 left-3 flex items-center pointer-events-none"
      >
        <Terminal class={`w-4 h-4 ${currentTheme.text} opacity-50`} />
      </div>
      <input
        type="text"
        bind:value={input}
        placeholder="Enter query..."
        class={`w-full bg-black/50 border border-white/20 rounded pl-10 pr-4 py-3 focus:outline-none focus:border-opacity-100 transition-colors ${currentTheme.text} ${currentTheme.border} placeholder-gray-600`}
        disabled={isLoading}
      />
      <button
        type="submit"
        disabled={isLoading}
        class={`px-4 rounded font-bold uppercase tracking-wider transition-all disabled:opacity-50 disabled:cursor-not-allowed ${currentTheme.button} text-white`}
      >
        <Send class="w-5 h-5" />
      </button>
    </div>
  </form>
</div>
